nohup: ignoring input
/home/amingk/Documents/7TPD/ActStimRL/Model/run_models/./hier/hierRL_med_cond_block_transfer_group13.py:49: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  behAll_group.sub_ID = behAll_group.sub_ID.replace(np.unique(behAll_group.sub_ID), np.arange(1, nParts +1))
/home/amingk/Documents/7TPD/ActStimRL/Model/run_models/./hier/hierRL_med_cond_block_transfer_group13.py:49: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  behAll_group.sub_ID = behAll_group.sub_ID.replace(np.unique(behAll_group.sub_ID), np.arange(1, nParts +1))
Building...

Building: 58.5s, done.Messages from stanc:
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 191, column 48: The
    variable soft_max_EV may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 183, column 30: The
    variable soft_max_EV may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 143, column 117: The
    variable p_blue may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 143, column 20: The
    variable p_blue may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 139, column 117: The
    variable p_yell may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 139, column 20: The
    variable p_yell may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 135, column 118: The
    variable p_pull may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 135, column 21: The
    variable p_pull may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 131, column 118: The
    variable p_push may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 131, column 21: The
    variable p_push may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 112, column 18: The
    variable p_blue may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 111, column 18: The
    variable p_yell may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 110, column 18: The
    variable p_pull may not have been assigned a value before its use.
Warning in '/tmp/httpstan_hlkj_jb2/model_gdb5mpeb.stan', line 109, column 18: The
    variable p_push may not have been assigned a value before its use.
Traceback (most recent call last):
  File "/home/amingk/Documents/7TPD/ActStimRL/Model/run_models/./hier/hierRL_med_cond_block_transfer_group13.py", line 96, in <module>
    posterior = stan.build(stan_model, data = dataStan)
  File "/mrhome/amingk/.local/lib/python3.9/site-packages/stan/model.py", line 519, in build
    return asyncio.run(go())
  File "/mrhome/amingk/.local/lib/python3.9/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/mrhome/amingk/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/mrhome/amingk/anaconda3/envs/7tpd/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/mrhome/amingk/anaconda3/envs/7tpd/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/mrhome/amingk/.local/lib/python3.9/site-packages/stan/model.py", line 511, in go
    raise RuntimeError(resp.json()["message"])
RuntimeError: Error calling get_param_names: `Exception: variable does not exist; processing stage=data initialization; variable name=nBlocks; base type=int (in '/tmp/httpstan_9gyw9_ra/model_gdb5mpeb.stan', line 21, column 4 to column 25)`
